import { Provider } from '@/components/Provider';
import { Header } from '@/components/header';
import type { Metadata } from 'next';
import 'react-toastify/dist/ReactToastify.css';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-black'>
        <Provider>
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-start p-20">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
